
# Name your project! Project names should be lowercase and use underscores as separators
name: 'dbt_02_21_26_project'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_02_21_26_profile'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["data"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]
target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
# Full documentation: https://docs.getdbt.com/docs/configuring-models

models:
  dbt_02_21_26_project:
    # Config indicated by + and applies to all files under models/staging/
    
    staging:
      +materialized: view
      +schema: staging
      +tags: [staging]
    
    prod:
      +materialized: view
      +schema: prod
      +tags: [prod]
    # Config indicated by + and applies to all files under models/marts/
    
    marts:
      +materialized: table
      +schema: marts
      +tags: [marts]
