# Profile for BigQuery example
example_analytics:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: oauth 
      project: 'dbt-bigquery-integration'
      dataset: 'dbt_02_21_26'
      threads: 4
      timeout_seconds: 300
      location: 'US'
      priority: interactive
      retries: 1
      keyfile: '/home/hanse/Documents/BigQuery/keyfile.json'

    staging:
      type: bigquery
      method: oauth 
      project: 'dbt-bigquery-integration'
      dataset: 'dbt_02_21_26_staging'
      threads: 4
      timeout_seconds: 300
      location: 'US'
      priority: interactive
      retries: 1
      keyfile: '/home/hanse/Documents/BigQuery/keyfile.json'
    
    prod:
      type: bigquery
      method: oauth
      project: 'dbt-bigquery-integration'
      dataset: 'dbt_02_21_26_prod'
      threads: 8
      timeout_seconds: 300
      location: 'US'
      priority: interactive
      keyfile:  '/home/hanse/Documents/BigQuery/keyfile.json'

