name: dbt tests
on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main

env:
  DBT_PROFILES_DIR: ./

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      
      - name: Install dbt
        run: |
          pip install dbt-bigquery
          dbt --version
      
      - name: Install dependencies
        run: dbt deps
      
      - name: Run dbt tests
        run: dbt test
      
      - name: Run dbt build
        run: dbt build
